Traceback (most recent call last):
  File "/home/ricardo/Google_IT_Automation_with_Python_Professional_Certificate/COURSE_2_Using_Python_to_Interact_with_the_Operating_System/Week6/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
Traceback (most recent call last):
  File "/home/ricardo/Google_IT_Automation_with_Python_Professional_Certificate/COURSE_2_Using_Python_to_Interact_with_the_Operating_System/Week6/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
